"""esquema inicial

Revision ID: 2b2d05cab2e8
Revises: 
Create Date: 2026-08-05 08:42:45.524547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b2d05cab2e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensors_name'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_reading_timestamp'), table_name='readings')
    op.drop_index(op.f('ix_readings_hash_id'), table_name='readings')
    op.drop_table('readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('hash_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('readings_sensor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('readings_pkey')),
    sa.UniqueConstraint('sensor_id', 'hash_id', name=op.f('unique_hash'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_readings_hash_id'), 'readings', ['hash_id'], unique=False)
    op.create_index(op.f('ix_reading_timestamp'), 'readings', ['sensor_id', 'timestamp'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sensors_pkey'))
    )
    op.create_index(op.f('ix_sensors_name'), 'sensors', ['name'], unique=True)
    # ### end Alembic commands ###
