"""refactorizacion de la interfaz de errores para el usuario

Revision ID: 6acc2a8a5eaf
Revises: 883e0fe7d0a1
Create Date: 2026-08-14 03:46:28.492972

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6acc2a8a5eaf"
down_revision: str | Sequence[str] | None = "883e0fe7d0a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alerts", sa.Column("state", sa.String(), nullable=False))
    op.add_column("sensors", sa.Column("ubication", sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sensors", "ubication")
    op.drop_column("alerts", "state")
    # ### end Alembic commands ###
