"""correcciones de AI_CODE_REVIEW.md

Revision ID: 73820e5a5cca
Revises: ea4abde2e8e4
Create Date: 2026-08-15 03:58:31.916905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73820e5a5cca'
down_revision: Union[str, Sequence[str], None] = 'ea4abde2e8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
