"""actualizacion para umbrales y alertas

Revision ID: 883e0fe7d0a1
Revises: 2b2d05cab2e8
Create Date: 2026-08-13 00:10:42.892741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883e0fe7d0a1'
down_revision: Union[str, Sequence[str], None] = '2b2d05cab2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'alerts',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('sensor_id', sa.Integer(), nullable=False),
        sa.Column('reading_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('value', sa.Float(precision=53), nullable=False),
        sa.Column('unit', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['sensor_id'], ['sensors.id'],
            name=op.f('alerts_sensor_id_fkey'),
        ),
        sa.ForeignKeyConstraint(
            ['reading_id'], ['readings.id'],
            name=op.f('alerts_reading_id_fkey'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey')),
    )
    op.add_column('sensors', sa.Column('threshold_min', sa.Float(), nullable=False))
    op.add_column('sensors', sa.Column('threshold_max', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'threshold_max')
    op.drop_column('sensors', 'threshold_min')
    op.drop_table('alerts')
    # ### end Alembic commands ###
