"""actualizacion para umbrales y alertas

Revision ID: 883e0fe7d0a1
Revises: 2b2d05cab2e8
Create Date: 2026-08-13 00:10:42.892741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883e0fe7d0a1'
down_revision: Union[str, Sequence[str], None] = '2b2d05cab2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('threshold_min', sa.Float(), nullable=False))
    op.add_column('sensors', sa.Column('threshold_max', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'threshold_max')
    op.drop_column('sensors', 'threshold_min')
    # ### end Alembic commands ###
